const USER_ROLES = {
  ADMIN: "ADMIN",
  STAFF: "STAFF",
  CUSTOMER: "CUSTOMER",
};

const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

const PAYMENT_METHODS = {
  CASH: "CASH",
  UPI: "UPI",
  BANK: "BANK",
  CARD: "CARD",
};

const PAYMENT_STATUS = {
  SUCCESS: "SUCCESS",
  REVERSED: "REVERSED",
  CORRECTED: "CORRECTED",
  CANCELLED: "CANCELLED",
};

const SCHEME_STATUS = {
  ACTIVE: "ACTIVE",
  REDEEMED: "REDEEMED",
  CLOSED: "CLOSED",
};

const SETTLEMENT_STATUSES = [SCHEME_STATUS.REDEEMED, SCHEME_STATUS.CLOSED];

const CORRECTION_TYPES = {
  EDIT_AMOUNT: "EDIT_AMOUNT",
  EDIT_METHOD: "EDIT_METHOD",
  EDIT_DATE: "EDIT_DATE",
  EDIT_REFERENCE: "EDIT_REFERENCE",
  EDIT_NOTES: "EDIT_NOTES",
  REVERSE_PAYMENT: "REVERSE_PAYMENT",
};

const CORRECTION_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

const SETTLEMENT_WORKFLOW_STATUS = {
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  PAYOUT_PENDING: "PAYOUT_PENDING",
  PAID: "PAID",
  FINALIZED: "FINALIZED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

const JOURNAL_EVENT_TYPES = {
  COLLECTION_RECEIVED: "COLLECTION_RECEIVED",
  COLLECTION_ADJUSTMENT: "COLLECTION_ADJUSTMENT",
  COLLECTION_REVERSAL: "COLLECTION_REVERSAL",
  STAFF_CASH_RECEIVED: "STAFF_CASH_RECEIVED",
  STAFF_CASH_SUBMITTED: "STAFF_CASH_SUBMITTED",
  VAULT_ADJUSTMENT: "VAULT_ADJUSTMENT",
  VAULT_REVERSAL: "VAULT_REVERSAL",
  SETTLEMENT_ENTITLEMENT_RECOGNIZED: "SETTLEMENT_ENTITLEMENT_RECOGNIZED",
  SETTLEMENT_AUTHORIZED: "SETTLEMENT_AUTHORIZED",
  SETTLEMENT_PAID: "SETTLEMENT_PAID",
  SETTLEMENT_REVERSAL: "SETTLEMENT_REVERSAL",
};

const IDEMPOTENCY_OPERATIONS = {
  PAYMENT_COLLECT: "PAYMENT_COLLECT",
  CASH_SUBMISSION: "CASH_SUBMISSION",
  SCHEME_SETTLEMENT: "SCHEME_SETTLEMENT",
  SETTLEMENT_PAYOUT: "SETTLEMENT_PAYOUT",
  SETTLEMENT_FINALIZE: "SETTLEMENT_FINALIZE",
  PAYMENT_REVERSE: "PAYMENT_REVERSE",
  CORRECTION_APPROVE: "CORRECTION_APPROVE",
  CORRECTION_REJECT: "CORRECTION_REJECT",
  SCHEME_CREATE: "SCHEME_CREATE",
  CASH_SUBMISSION_REVERSE: "CASH_SUBMISSION_REVERSE",
};

const CASH_SUBMISSION_STATUS = {
  ACTIVE: "ACTIVE",
  REVERSED: "REVERSED",
};

const DELETION_REQUEST_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  EXECUTED: "EXECUTED",
};

const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  PASSWORD_RESET: "PASSWORD_RESET",
  STAFF_PERMISSIONS_UPDATED: "STAFF_PERMISSIONS_UPDATED",
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  CUSTOMER_PASSWORD_RESET: "CUSTOMER_PASSWORD_RESET",
  STAFF_CREATED: "STAFF_CREATED",
  STAFF_UPDATED: "STAFF_UPDATED",
  PAYMENT_COLLECTED: "PAYMENT_COLLECTED",
  PAYMENT_REVERSED: "PAYMENT_REVERSED",
  PAYMENT_CORRECTED: "PAYMENT_CORRECTED",
  CORRECTION_REQUESTED: "CORRECTION_REQUESTED",
  CORRECTION_APPROVED: "CORRECTION_APPROVED",
  CORRECTION_REJECTED: "CORRECTION_REJECTED",
  CASH_SUBMITTED: "CASH_SUBMITTED",
  CASH_SUBMISSION_REVERSED: "CASH_SUBMISSION_REVERSED",
  SCHEME_REDEEMED: "SCHEME_REDEEMED",
  SCHEME_CLOSED: "SCHEME_CLOSED",
  SCHEME_CREATED: "SCHEME_CREATED",
  ADMIN_OVERRIDE_USED: "ADMIN_OVERRIDE_USED",
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  DELETION_REQUEST_STATUS,
  PAYMENT_METHODS,
  PAYMENT_STATUS,
  SCHEME_STATUS,
  SETTLEMENT_STATUSES,
  SETTLEMENT_WORKFLOW_STATUS,
  JOURNAL_EVENT_TYPES,
  CORRECTION_TYPES,
  CORRECTION_STATUS,
  CASH_SUBMISSION_STATUS,
  IDEMPOTENCY_OPERATIONS,
  AUDIT_ACTIONS,
};
