const USER_ROLES = {
  ADMIN: "ADMIN",
  STAFF: "STAFF",
  CUSTOMER: "CUSTOMER",
};

const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

const PAYMENT_METHODS = {
  CASH: "CASH",
  UPI: "UPI",
  BANK: "BANK",
  CARD: "CARD",
};

const PAYMENT_STATUS = {
  SUCCESS: "SUCCESS",
  REVERSED: "REVERSED",
  CORRECTED: "CORRECTED",
  CANCELLED: "CANCELLED",
};

const SCHEME_STATUS = {
  ACTIVE: "ACTIVE",
  REDEEMED: "REDEEMED",
  CLOSED: "CLOSED",
};

const SETTLEMENT_STATUSES = [SCHEME_STATUS.REDEEMED, SCHEME_STATUS.CLOSED];

const CORRECTION_TYPES = {
  EDIT_AMOUNT: "EDIT_AMOUNT",
  EDIT_METHOD: "EDIT_METHOD",
  EDIT_DATE: "EDIT_DATE",
  EDIT_REFERENCE: "EDIT_REFERENCE",
  EDIT_NOTES: "EDIT_NOTES",
  REVERSE_PAYMENT: "REVERSE_PAYMENT",
};

const CORRECTION_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

const DELETION_REQUEST_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  CUSTOMER_PASSWORD_RESET: "CUSTOMER_PASSWORD_RESET",
  STAFF_CREATED: "STAFF_CREATED",
  STAFF_UPDATED: "STAFF_UPDATED",
  PAYMENT_COLLECTED: "PAYMENT_COLLECTED",
  PAYMENT_REVERSED: "PAYMENT_REVERSED",
  PAYMENT_CORRECTED: "PAYMENT_CORRECTED",
  CORRECTION_REQUESTED: "CORRECTION_REQUESTED",
  CORRECTION_APPROVED: "CORRECTION_APPROVED",
  CORRECTION_REJECTED: "CORRECTION_REJECTED",
  DELETION_REQUESTED: "DELETION_REQUESTED",
  DELETION_REQUEST_CANCELLED: "DELETION_REQUEST_CANCELLED",
  CASH_SUBMITTED: "CASH_SUBMITTED",
  SCHEME_REDEEMED: "SCHEME_REDEEMED",
  SCHEME_CLOSED: "SCHEME_CLOSED",
  SCHEME_CREATED: "SCHEME_CREATED",
  ADMIN_OVERRIDE_USED: "ADMIN_OVERRIDE_USED",
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  PAYMENT_METHODS,
  PAYMENT_STATUS,
  SCHEME_STATUS,
  SETTLEMENT_STATUSES,
  CORRECTION_TYPES,
  CORRECTION_STATUS,
  DELETION_REQUEST_STATUS,
  AUDIT_ACTIONS,
};
