const USER_ROLES = {
  ADMIN: "ADMIN",
  STAFF: "STAFF",
  CUSTOMER: "CUSTOMER",
};

const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

const PAYMENT_METHODS = {
  CASH: "CASH",
  UPI: "UPI",
  BANK: "BANK",
  CARD: "CARD",
};

const PAYMENT_STATUS = {
  SUCCESS: "SUCCESS",
  REVERSED: "REVERSED",
  CORRECTED: "CORRECTED",
  CANCELLED: "CANCELLED",
};

const SCHEME_STATUS = {
  ACTIVE: "ACTIVE",
  MATURED: "MATURED",
  REDEEMED: "REDEEMED",
  CLOSED: "CLOSED",
  WITHDRAWN: "WITHDRAWN",
  SUSPENDED: "SUSPENDED",
};

const CORRECTION_TYPES = {
  WRONG_AMOUNT: "WRONG_AMOUNT",
  WRONG_CUSTOMER: "WRONG_CUSTOMER",
  WRONG_METHOD: "WRONG_METHOD",
  DUPLICATE: "DUPLICATE",
  OTHER: "OTHER",
};

const CORRECTION_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  CUSTOMER_PASSWORD_RESET: "CUSTOMER_PASSWORD_RESET",
  STAFF_CREATED: "STAFF_CREATED",
  STAFF_UPDATED: "STAFF_UPDATED",
  PAYMENT_COLLECTED: "PAYMENT_COLLECTED",
  PAYMENT_REVERSED: "PAYMENT_REVERSED",
  PAYMENT_CORRECTED: "PAYMENT_CORRECTED",
  CASH_SUBMITTED: "CASH_SUBMITTED",
  SCHEME_REDEEMED: "SCHEME_REDEEMED",
  SCHEME_CLOSED: "SCHEME_CLOSED",
  SCHEME_WITHDRAWN: "SCHEME_WITHDRAWN",
  SCHEME_CREATED: "SCHEME_CREATED",
  ADMIN_OVERRIDE_USED: "ADMIN_OVERRIDE_USED",
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  PAYMENT_METHODS,
  PAYMENT_STATUS,
  SCHEME_STATUS,
  CORRECTION_TYPES,
  CORRECTION_STATUS,
  AUDIT_ACTIONS,
};
