const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  TRANSACTION_RETRY_REQUIRED: "TRANSACTION_RETRY_REQUIRED",
  INSUFFICIENT_STAFF_CASH: "INSUFFICIENT_STAFF_CASH",
  CASH_BALANCE_CONFLICT: "CASH_BALANCE_CONFLICT",
  SCHEME_ALREADY_SETTLED: "SCHEME_ALREADY_SETTLED",
  PAYMENT_AFTER_SETTLEMENT: "PAYMENT_AFTER_SETTLEMENT",
  PAYMENT_ALREADY_REVERSED: "PAYMENT_ALREADY_REVERSED",
  CORRECTION_ALREADY_REVIEWED: "CORRECTION_ALREADY_REVIEWED",
  PENDING_CORRECTION_EXISTS: "PENDING_CORRECTION_EXISTS",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

const STATUS_DEFAULTS = {
  400: { code: ERROR_CODES.VALIDATION_ERROR, retryable: false },
  401: { code: ERROR_CODES.UNAUTHORIZED, retryable: false },
  403: { code: ERROR_CODES.FORBIDDEN, retryable: false },
  404: { code: ERROR_CODES.NOT_FOUND, retryable: false },
  429: { code: ERROR_CODES.RATE_LIMITED, retryable: false },
  500: { code: ERROR_CODES.INTERNAL_ERROR, retryable: false },
};

const resolveErrorMeta = (error) => {
  const statusCode = error?.statusCode || 500;
  const defaults = STATUS_DEFAULTS[statusCode] || STATUS_DEFAULTS[500];

  return {
    code: error?.code ?? defaults.code,
    retryable: error?.retryable ?? defaults.retryable ?? false,
  };
};

module.exports = {
  ERROR_CODES,
  STATUS_DEFAULTS,
  resolveErrorMeta,
};
