const JOURNAL_ACCOUNTS = {
  CUSTOMER_SCHEME_LIABILITY: "CUSTOMER_SCHEME_LIABILITY",
  STAFF_CASH_CUSTODY: "STAFF_CASH_CUSTODY",
  VAULT: "VAULT",
  SETTLEMENT_PAYABLE: "SETTLEMENT_PAYABLE",
};

module.exports = {
  JOURNAL_ACCOUNTS,
};
